phrase:
  access_token: null
  project_id: null
  push:
    sources:
    - file: ./locales/<locale_name>.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./locales/<locale_name>.json
      params:
        file_format: simple_json
