# description:dinamically substitution  of values
name: variable substitution in json

on:
  workflow_dispatch

jobs:
build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1 
    with:
        files: 'employee.json'
    env:
        username: tcranz
        password: ${{ secrets.SECRET1 }}
        url: https://github.com/${{github.repository}}
