# Phrase.yml
name: Phrase translations
on:  
  workflow_dispatch:

jobs:
#Pull Phrase Translations 
  pull-phrase:
    runs-on: ubuntu-latest
    steps:
      - name: Getting up to date phrase data
        uses: actions/checkout@v3

     #  - name: Setting up nodejs 16 environment
     #    uses: actions/setup-node@v1
     #    with:
     #      node-version: '16.x'    
     #  - name: Install packages with yarn
     #    run: yarn install     
      - name: Phrase app
        uses: winify-ag/setup-phraseapp@v2
        with:
          version: 2.0.12
      - name: change values
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'employee.json'
        env:
          access_token: tcranz

      - run: phrase pull
      - name: Save translations to artifact
        uses: actions/upload-artifact@v3
        with:
          name: translations
          path: ./locales/*
    
      # - uses: EndBug/add-and-commit@v9
      #  with:
       #   message: 'Adding placeholder json file'
        #  add: './locales/*.json --force'
         # cwd: '.'
